services:
  php-cli-ebics-client-php:
    container_name: php-cli-ebics-client-php
    build:
      context: php-cli
    image: php-cli-ebics-client-php:8.5.4-cli
    volumes:
      - ~/.ssh:/home/root/.ssh
      - ../:/var/www/ebics-client-php
      - ./php-cli/php.ini:/usr/local/etc/php/php.ini:ro
      - ~/.bash_history:/home/root/.bash_history
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    environment:
      PHP_IDE_CONFIG: "serverName=ebics-client-php"
