<?php

namespace EbicsApi\Ebics\Contracts;

/**
 * EBICS Transaction base interface.
 *
 * Represents a transaction between the client and the bank server.
 * Serves as the base contract for download, upload, and initialization
 * transactions within the EBICS protocol.
 *
 * In the EBICS protocol, a transaction encompasses the complete lifecycle
 * of a data exchange operation — from initialization through data transfer
 * to final receipt acknowledgment. Each transaction is uniquely identified
 * by a transaction key (transaction ID) assigned by the bank during the
 * initialization phase.
 *
 * Concrete implementations include:
 * - {@see InitializationTransactionInterface}: For INI, HIA, H3K, HPB orders
 * - {@see DownloadTransactionInterface}: For file download operations
 * - {@see UploadTransactionInterface}: For file upload operations
 *
 * @license http://www.opensource.org/licenses/mit-license.html  MIT License
 * @author Andrew Svirin
 */
interface TransactionInterface
{
    /**
     * Get the transaction key (unique identifier assigned by the bank).
     *
     * The transaction key (also called Transaction ID) is generated by the
     * bank server during the transaction initialization phase and is used
     * to reference the transaction in subsequent requests (e.g., data
     * retrieval, receipt acknowledgment).
     *
     * @return string The unique transaction identifier
     */
    public function getKey(): string;
}
